Chore/announcement test
tech-university-india/abd-backend pull request #29
Opened 2023-02-21 11:30 UTC by Abhishek-Kharpal

This PR includes: 
* Tests covering 100% of announcements endpoints
* Fix for wrong status code on invalid id in edit and delete of announcement.

2023-03-05 17:28 UTC, samim-hossain-mondal commented on tests/controllers/dsm/announcements.test.js
> +  const announcements = [
you can shift these mocked datas to a constant file like made folder outside of src -> mocks -> dsm -> announcements.js 
so that once you import the data and use anywhere !

2023-03-05 17:28 UTC, samim-hossain-mondal commented on tests/services/dsm/announcements.test.js
> +      const mockAnnouncements = [
same for all

2023-03-05 17:30 UTC, samim-hossain-mondal commented on tests/controllers/dsm/announcements.test.js
> +    }
you can shift these mocked datas to a constant file like made folder outside of src -> mocks -> dsm -> announcements.js
so that once you import the data and use anywhere !

2023-03-05 17:30 UTC, samim-hossain-mondal commented on tests/services/dsm/announcements.test.js
> +          createdAt: '2021-04-05T11:00:00.000Z',
same for all

2023-03-05 17:31 UTC, samim-hossain-mondal commented on tests/controllers/dsm/announcements.test.js
> +      author: '1',
you can shift these mocked datas to a constant file like made folder outside of src -> mocks -> dsm -> announcements.js
so that once you import the data and use anywhere !

2023-03-05 17:31 UTC, samim-hossain-mondal commented on tests/services/dsm/announcements.test.js
> +          content: 'test',
same for all

2023-03-06 08:51 UTC, Harshit-Soni-Mck requested changes
define constants in separate file as already mentioned by @samim-hossain-mondal

2023-03-06 11:25 UTC, Abhishek-Kharpal commented on tests/controllers/dsm/announcements.test.js
> +      author: '1',
Done in commit https://github.com/tech-university-india/abd-backend/pull/29/commits/5828300dd7e4909121ba90e650a994ce5f7c7d2c

2023-03-06 11:25 UTC, Abhishek-Kharpal commented on tests/services/dsm/announcements.test.js
> +          content: 'test',
Done in commit https://github.com/tech-university-india/abd-backend/pull/29/commits/5828300dd7e4909121ba90e650a994ce5f7c7d2c

2023-03-06 11:26 UTC, Abhishek-Kharpal commented
> define constants in separate file as already mentioned by @samim-hossain-mondal

Done in commit https://github.com/tech-university-india/abd-backend/pull/29/commits/5828300dd7e4909121ba90e650a994ce5f7c7d2c

2023-03-06 11:33 UTC, samim-hossain-mondal commented
> > define constants in separate file as already mentioned by @samim-hossain-mondal
> 
> Done in commit [5828300](https://github.com/tech-university-india/abd-backend/commit/5828300dd7e4909121ba90e650a994ce5f7c7d2c)

LGTM

2023-03-06 11:34 UTC, samim-hossain-mondal commented on tests/services/dsm/announcements.test.js
> +          content: 'test',
LGTM

2023-03-14 06:03 UTC, merged